config/routes.rb
Rails.application.routes.draw do


root "pages#root"


  # Routes for the Company resource:

  # CREATE
  post("/insert_company", { :controller => "companies", :action => "create" })

  # READ
  get("/companies", { :controller => "companies", :action => "index" })

  get("/companies/:path_id", { :controller => "companies", :action => "show" })

  # UPDATE

  post("/modify_company/:path_id", { :controller => "companies", :action => "update" })

  # DELETE
  get("/delete_company/:path_id", { :controller => "companies", :action => "destroy" })

  #------------------------------

  # Routes for the Job description resource:

  # CREATE
  post("/insert_job_description", { :controller => "job_descriptions", :action => "create" })

  # READ
  get("/job_descriptions", { :controller => "job_descriptions", :action => "index" })

  get("/job_descriptions/:path_id", { :controller => "job_descriptions", :action => "show" })

  # UPDATE

  post("/modify_job_description/:path_id", { :controller => "job_descriptions", :action => "update" })

  # DELETE
  get("/delete_job_description/:path_id", { :controller => "job_descriptions", :action => "destroy" })

  #------------------------------

  # Routes for the Job application resource:

  get("/job_applications/new", { :controller => "job_applications", :action=> "new" })

  # CREATE
  post("/insert_job_application", { :controller => "job_applications", :action => "create" })

  # READ
  get("/job_applications", { :controller => "job_applications", :action => "index" })

  get("/job_applications/:path_id", { :controller => "job_applications", :action => "show" })

  # UPDATE

  post("/modify_job_application/:path_id", { :controller => "job_applications", :action => "update" })

  # DELETE
  get("/delete_job_application/:path_id", { :controller => "job_applications", :action => "destroy" })

  #------------------------------

  devise_for :users
  # This is a blank app! Pick your first screen, build out the RCAV, and go from there. E.g.:
  # get("/your_first_screen", { :controller => "pages", :action => "first" })
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
  <div class="container">
    <%= link_to "JobTrack", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>

        <% end %>
      </ul>

      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to job_applications_new_path, class: "nav-link" do %>
              <i class="fas fa-plus-circle"></i>

              Add Application
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.email %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>